stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/prepared/train.csv
    - data/prepared/test.csv
  train:
    cmd: python src/train.py
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/model.joblib
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - model/model.joblib
    - src/evaluate.py
    metrics:
    - metrics/accuracy.json:
        cache: false
artifacts:
  SGD_100_epochs:
    path: model/model.joblib
    type: model
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
